### ISSUE TITLE
is it not possible to use it with vite?

### ISSUE THREAD

**Issue by swana1337** [joaomede/vue3-json-editor#1]

**Comment by joaoportlouis** [comment]
I didn't take the ESM test, but the package offers ESM Yes!

**Comment by joaomede** [comment]
I didn't take the ESM test, but the package offers ESM Yes!

**Comment by swana1337** [comment]
i found a way to use it with vite. i needed to import like this

import { Vue3JsonEditor } from 'vue3-json-editor/dist/vue3-json-editor.esm'


but it cant show the icons from jsoneditor-icons.svg. its always error 404

**Comment by joaomede** [comment]
yes, there is a problem with svg, this is a point that needs to be fixed, it happened when I converted the original project to vue 3x version

**Comment by swana1337** [comment]
okay thank you to let me know ! :D

**Comment by swana1337** [comment]
will there be an update for this?

**Comment by joaomede** [comment]
@swana1337  yes, there is already an issue, this week I will make a release and let you know here.

**Comment by swana1337** [comment]
thanks a lot :)

**Comment by joaomede** [comment]
hello @swana1337, the fix is ​​now available, version 1.1.1

**Comment by swana1337** [comment]
i tried it, sadly nothing is working anymore now at my end. but thanks to let me know :)

**Comment by joaomede** [comment]
I made a new fix, version 1.1.2.

changelog:
* Fix ESM Module
* Added Demo vitejs project
* Fixed package.json with path to ESM module.

please be sure to see the vite example before implementing it in your project.
