### ISSUE TITLE
I set it in Chinese but it still seems to be in English;

### ISSUE THREAD

**Issue by lrx1991** [joaomede/vue3-json-editor#13]
<Vue3-json-editor v-model="jsonEditor.json"
                        class="scrollbar"
                        style="width: 100%;height: 100%;overflow: hidden;"
                        :expandedOnStart="false"
                        mode="form"
                        **lang="zh"**
                        @json-change="onJsonChange" />

**Comment by joaomede** [comment]
你好
thanks for informing, i will validate.

**Comment by joaomede** [comment]
你好。- Hi

Currently only the save button is translated, this button is an optional feature, it is only visible if you set the "showBtns" property

![Captura de tela de 2021-10-30 12-35-16](https://user-images.githubusercontent.com/49351989/139539721-56f6bc07-c5bd-4e78-81e0-2783adb01551.png)

**Comment by joaomede** [comment]
你好。- Hi

Currently only the save button is translated, this button is an optional feature, it is only visible if you set the "showBtns" property
![Captura de tela de 2021-10-30 12-35-16](https://user-images.githubusercontent.com/49351989/139539812-3c26b7f0-3f81-4c70-bbba-3f8925247a6f.png)
