### ISSUE TITLE
Multiple json editors in same page are rendered in the same wrapper div

### ISSUE THREAD

**Issue by xys777** [joaomede/vue3-json-editor#14]
// add a id to identify the different components can fix this issue

const uid = getCurrentInstance().uid;

state.editor = new JsonEditor(
        document.querySelector('.jsoneditor-vue-' + uid),
        options,
        state.json
      )

<div class={'jsoneditor-vue-' + uid}></div>

**Comment by joaomede** [comment]
Thank you

**Comment by daidaishuo** [comment]
same question in vue3-json-editor 1.1.3 version , is this bug fixed?

**Comment by joaomede** [comment]
> same question in vue3-json-editor 1.1.3 version , is this bug fixed? 

Yes, but not released yet, i Do It today

**Comment by joaomede** [comment]
@daidaishuo new release https://github.com/joaomede/vue3-json-editor/releases/tag/v1.1.4

**Comment by gustavorps** [comment]
@joaomede 
Is the same version at [NPM](https://www.npmjs.com/package/vue3-json-editor/v/1.1.4)?

**Comment by joaomede** [comment]
@gustavorps Yes

**Comment by johanmaes** [comment]
Hi @joaomede, thanks for the work on this package. Is it possible that this fix didn't get deployed in v1.1.4? When I clone and build a local version everything works as expected. But when I use the npm package, multiple editors still end up in the same container div.

**Comment by joaomede** [comment]
Hey Guy @johanmaes, thanks for your time, I made an update

Fixed: https://github.com/joaomede/vue3-json-editor/commit/2112d928b28268be2412e4f68eb65cd02d09309e
NPM: https://www.npmjs.com/package/vue3-json-editor/v/1.1.5
