### ISSUE TITLE
n.editor is null

### ISSUE THREAD

**Issue by brms2021** [joaomede/vue3-json-editor#15]
Hi folks,
Tried using your test examples in a Vue 3 Project but cannot get it working (error: **n.editor is null**)
![image](https://user-images.githubusercontent.com/86517410/144316734-f5ccb189-31c6-4d2b-9b54-df4fa7381e4a.png)

**Comment by joaomede** [comment]
hi, you can show a example of project? If you can, i can fix the problem, thank you

**Comment by joaomede** [comment]
Fixed: https://github.com/joaomede/vue3-json-editor/commit/2112d928b28268be2412e4f68eb65cd02d09309e
NPM: https://www.npmjs.com/package/vue3-json-editor/v/1.1.5
