### ISSUE TITLE
jsoneditor-icons.svg. its always error 404

### ISSUE THREAD

**Issue by joaomede** [joaomede/vue3-json-editor#2]
When using the component, in any usage mode, there is a problem when importing or an icon in .svg (no console). this problem (maybe) it is possible to solve it improve the rollup, however it is necessary to investigate, it occurred due to "improvement" of the component version vue2 to vue3.

**Comment by augustoOliveira1993** [comment]
eu corrigo!

**Comment by joaomede** [comment]
#4 fixed
