### ISSUE TITLE
Error when using

### ISSUE THREAD

**Issue by muhan-666** [joaomede/vue3-json-editor#6]
![image](https://user-images.githubusercontent.com/55844132/126865011-1c3f2624-c3c4-4aca-bf0c-b22fcbf2a91d.png)
TypeError: Cannot read property 'includes' of undefined

**Comment by joaomede** [comment]
hi, can you give me more details of this bug?

**Comment by muhan-666** [comment]
> hi, can you give me more details of this bug?

![image](https://user-images.githubusercontent.com/55844132/126921703-14d81399-72d9-42f2-a99f-7e13959dc8e5.png)
this is my code

**Comment by joaomede** [comment]
@muhan-666 fixed
