### ISSUE TITLE
can i use it with v-for?

### ISSUE THREAD

**Issue by yaojiawei666** [joaomede/vue3-json-editor#7]
i use this editor with v-for, but all the editors under .jsoneditor-vue, how can i do

**Comment by yaojiawei666** [comment]
![screenshot-20210727-003655](https://user-images.githubusercontent.com/45327143/127026118-cae50e89-c382-4a22-a044-f2ae0167bc3e.png)
maybe i can modify container

**Comment by yaojiawei666** [comment]
@joaomede

**Comment by joaomede** [comment]
How is this problem? already managed to solve? need help?

**Comment by yaojiawei666** [comment]
const instance = getCurrentInstance()?.proxy;

state.editor = new JsonEditor(
        instance?.$el.querySelector(".jsoneditor-vue"),
        options,
        state.json
      );
i resolved this problem by change the element which mounted
it will cause some bugs? i don't sure about that.

**Comment by joaomede** [comment]
using the $ "el.querySelector" would be the choice of the original component, however, I noticed that this didn't work in vue3, so I'm using "document.querySelector", but I'll look at your suggestion.
