### ISSUE TITLE
when I use vue3-json-editor I got a error TypeError: Cannot read property 'getMode' of null

### ISSUE THREAD

**Issue by jianshe** [joaomede/vue3-json-editor#9]
Cannot read property 'getMode' of null
Please help me to deal with it .

Thank you.
            joaomede

**Comment by joaomede** [comment]
please, show your implementation

**Comment by juanfriss** [comment]
Just importing this got me the same error.

**Comment by joaomede** [comment]
Guys, there are example implementations in the repository itself, please test the examples. https://github.com/joaomede/vue3-json-editor/blob/master/src/App.vue

https://github.com/joaomede/vue3-json-editor/blob/master/example_vite/App.vue

**Comment by linqinghao** [comment]
got the same error

**Comment by joaomede** [comment]
To test with "vite", run the command "npm run dev vue"
to test with "Vue3", run the command "npm run dev"
Currently I haven't identified any problems in the examples in the project, please use the examples to test the cases.

**Comment by hjklink** [comment]
![image](https://user-images.githubusercontent.com/47598373/141397996-062afb81-0d85-4935-9faa-4d313079f174.png)

![image](https://user-images.githubusercontent.com/47598373/141398016-c0c35a29-e808-44b6-9ac4-fcda42af5d54.png)

same error

**Comment by wellingtonfetchly** [comment]
![Screen Shot 2022-01-28 at 17 44 36](https://user-images.githubusercontent.com/87502560/151618757-116baf8b-df63-4301-bba5-58af44107065.png)
Same error here

**Comment by hakuna0829** [comment]
I've got same error.
I've created new project using quasar with vue 3.0 cli and followed readme from `vue3-json-editor` package like above.
Is there any solution?

**Comment by wellingtonfetchly** [comment]
The problem was already solved in this commit [fixed gitMode null bug](https://github.com/joaomede/vue3-json-editor/commit/85ec755f80b2f64074b5709cf4419db8cac03351), but the file `dist/vue3-json-editor.esm.js` in `node_modules` is still with the old code
![Screen Shot 2022-01-31 at 10 28 36](https://user-images.githubusercontent.com/87502560/151802020-07a01541-a542-4e8c-85e0-8e3bb90880b4.png)

**Comment by hakuna0829** [comment]
Thanks @wellingtonfetchly.
Then, what shall I do? Need to change it inside node_moudles?

**Comment by wellingtonfetchly** [comment]
Hey @hakuna0829, I'm not sure either, I'm having the same problem.

**Comment by wellingtonfetchly** [comment]
It worked for me to update `vue` version to `3.2.29`

**Comment by joaomede** [comment]
Fixed: https://github.com/joaomede/vue3-json-editor/commit/2112d928b28268be2412e4f68eb65cd02d09309e
NPM: https://www.npmjs.com/package/vue3-json-editor/v/1.1.5
